{
 "title": "APM - Service Detail",
 "tags": [
  "apm",
  "datadog",
  "service",
  "detail"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Select Service",
    "query": "query_result(label_replace(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name!=\"pgbouncer\"}, \"service\", \"$1\", \"service_name\", \"(.+)\") or label_replace(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", server_address!=\"pgbouncer\"}, \"service\", \"$1\", \"server_address\", \"(.+)\"))"
   },
   {
    "name": "environment",
    "query": "label_values(otel_traces_span_metrics_calls_total, deployment_environment)"
   },
   {
    "name": "application",
    "query": "label_values(otel_traces_span_metrics_calls_total, application)"
   },
   {
    "name": "status",
    "query": "STATUS_CODE_OK,STATUS_CODE_ERROR,STATUS_CODE_UNSET"
   },
   {
    "name": "endpoint",
    "query": "label_values(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_INTERNAL\"}, http_route)"
   },
   { "name": "compare_window", "query": "1h,1d,7d" }
  ]
 },
 "panels": [
  { "title": "Health (${service})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Health Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", status_code=\"STATUS_CODE_ERROR\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\"}[$__range])) or label_replace(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", status_code=\"STATUS_CODE_ERROR\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\",http_route=~\"$endpoint\"}[$__range])), \"server_address\", \"$1\", \"service_name\", \"(.+)\")) / (sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\"}[$__range])) or label_replace(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\",http_route=~\"$endpoint\"}[$__range])), \"server_address\", \"$1\", \"service_name\", \"(.+)\")) * 100"
    }
   ]
  },
  {
   "title": "Throughput (Req/sec)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\"}[$__range])) or label_replace(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\",http_route=~\"$endpoint\"}[$__range])), \"server_address\", \"$1\", \"service_name\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(otel_traces_span_metrics_duration_milliseconds_bucket{span_kind=~\"SPAN_KIND_(SERVER|CLIENT)\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\"}[$__range])) by (le)) or histogram_quantile(0.95, sum(rate(otel_traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(otel_traces_span_metrics_duration_milliseconds_bucket{span_kind=~\"SPAN_KIND_(SERVER|CLIENT)\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\"}[$__range])) by (le)) or histogram_quantile(0.99, sum(rate(otel_traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", status_code=\"STATUS_CODE_ERROR\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\"}[$__range])) or label_replace(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", status_code=\"STATUS_CODE_ERROR\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\",http_route=~\"$endpoint\"}[$__range])), \"server_address\", \"$1\", \"service_name\", \"(.+)\")) / (sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\"}[$__range])) or label_replace(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\",http_route=~\"$endpoint\"}[$__range])), \"server_address\", \"$1\", \"service_name\", \"(.+)\")) * 100"
    }
   ]
  },
  {
   "title": "Throughput (${service})",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\"}[$__rate_interval])) by (status_code) or label_replace(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\",http_route=~\"$endpoint\"}[$__rate_interval])) by (status_code), \"server_address\", \"$1\", \"service_name\", \"(.+)\")",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\"}[$__rate_interval] offset $compare_window)) by (status_code) or label_replace(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\",http_route=~\"$endpoint\"}[$__rate_interval] offset $compare_window)) by (status_code), \"server_address\", \"$1\", \"service_name\", \"(.+)\")",
     "legendFormat": "Previous $compare_window"
    }
   ]
  },
  {
   "title": "Latency (${service})",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(otel_traces_span_metrics_duration_milliseconds_bucket{span_kind=~\"SPAN_KIND_(SERVER|CLIENT)\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\"}[$__rate_interval])) by (le)) or histogram_quantile(0.50, sum(rate(otel_traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50 Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(otel_traces_span_metrics_duration_milliseconds_bucket{span_kind=~\"SPAN_KIND_(SERVER|CLIENT)\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\"}[$__rate_interval])) by (le)) or histogram_quantile(0.95, sum(rate(otel_traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95 Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(otel_traces_span_metrics_duration_milliseconds_bucket{span_kind=~\"SPAN_KIND_(SERVER|CLIENT)\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\"}[$__rate_interval])) by (le)) or histogram_quantile(0.99, sum(rate(otel_traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99 Latency"
    }
   ]
  },
  {
   "title": "Error rate (${service})",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", status_code=\"STATUS_CODE_ERROR\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\"}[$__rate_interval])) or label_replace(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", status_code=\"STATUS_CODE_ERROR\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\",http_route=~\"$endpoint\"}[$__rate_interval])), \"server_address\", \"$1\", \"service_name\", \"(.+)\")) / (sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\"}[$__rate_interval])) or label_replace(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\",http_route=~\"$endpoint\"}[$__rate_interval])), \"server_address\", \"$1\", \"service_name\", \"(.+)\")) * 100",
     "legendFormat": "Current"
    },
    {
     "expr": "(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", status_code=\"STATUS_CODE_ERROR\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\"}[$__rate_interval] offset $compare_window)) or label_replace(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", status_code=\"STATUS_CODE_ERROR\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\",http_route=~\"$endpoint\"}[$__rate_interval] offset $compare_window)), \"server_address\", \"$1\", \"service_name\", \"(.+)\")) / (sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", server_address=~\"$service\", server_address!=\"pgbouncer\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\"}[$__rate_interval] offset $compare_window)) or label_replace(sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!=\"pgbouncer\", deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\",http_route=~\"$endpoint\"}[$__rate_interval] offset $compare_window)), \"server_address\", \"$1\", \"service_name\", \"(.+)\")) * 100",
     "legendFormat": "Previous $compare_window"
    }
   ]
  },
  { "title": "Dependencies (${service})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Downstream calls (${service})",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", service_name=~\"$service\", server_address!=\"pgbouncer\", server_address!=\"\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\"}[5m])) by (service_name, server_address, peer_service)",
     "legendFormat": "{{service_name}} -> {{server_address}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(otel_traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_CLIENT\", service_name=~\"$service\", server_address!=\"pgbouncer\", server_address!=\"\",deployment_environment=~\"$environment\",application=~\"$application\"}[5m])) by (le, service_name, server_address, peer_service))",
     "legendFormat": "{{service_name}} -> {{server_address}}"
    }
   ]
  },
  { "title": "Endpoints ()", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Request summary ()",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "round(label_replace(label_replace(sum(increase(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!~\".*(db|postgres|redis|pgbouncer).*\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\",http_route=~\"$endpoint\"}[$__range])) by (span_name, service_name), \"resource\", \"$1\", \"span_name\", \"(.+)\"), \"service\", \"$1\", \"service_name\", \"(.+)\"))",
     "legendFormat": "{{resource}}"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(otel_traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!~\".*(db|postgres|redis|pgbouncer).*\",deployment_environment=~\"$environment\",application=~\"$application\"}[$__range])) by (le, span_name)), \"resource\", \"$1\", \"span_name\", \"(.+)\")",
     "legendFormat": "{{resource}}"
    },
    {
     "expr": "round(label_replace(sum(increase(otel_traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", status_code=\"STATUS_CODE_ERROR\", service_name=~\"$service\", service_name!~\".*(db|postgres|redis|pgbouncer).*\",deployment_environment=~\"$environment\",application=~\"$application\",status_code=~\"$status\",http_route=~\"$endpoint\"}[$__range])) by (span_name), \"resource\", \"$1\", \"span_name\", \"(.+)\"))",
     "legendFormat": "{{resource}}"
    },
    {
     "expr": "label_replace(sum(increase(otel_traces_span_metrics_duration_milliseconds_sum{span_kind=\"SPAN_KIND_SERVER\", service_name=~\"$service\", service_name!~\".*(db|postgres|redis|pgbouncer).*\",deployment_environment=~\"$environment\",application=~\"$application\"}[$__range])) by (span_name), \"resource\", \"$1\", \"span_name\", \"(.+)\")",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}