apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://tempo:3200
    isDefault: true
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        tags:
          - key: service.name
            value: service_name
          - key: http.route
            value: http_route
        queries:
          - name: 'Request rate'
            query: 'sum(rate(otel_traces_span_metrics_calls_total{$$__tags}[5m]))'
          - name: 'P95 latency'
            query: 'histogram_quantile(0.95, sum(rate(otel_traces_span_metrics_duration_milliseconds_bucket{$$__tags}[5m])) by (le))'
      serviceMap:
        datasourceUid: prometheus

  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: false
    editable: true
